### ISSUE TITLE
升级最新homeassistant发送邮件功能就不能用了

### ISSUE THREAD

**Issue by qibao07** [shaonianzhentan/smtp#3]
![image](https://github.com/shaonianzhentan/smtp/assets/35797132/7d2b4143-bd44-4a60-9b6e-c98baad8156a)

![image](https://github.com/shaonianzhentan/smtp/assets/35797132/753d21bc-dfb3-4d0d-a226-ac1b76bd1ed1)

**Comment by shaonianzhentan** [comment]
升级到最新版本，重新安装即可
