### ISSUE TITLE
验证失败，请检查配置是否有误

### ISSUE THREAD

**Issue by haoyouandme** [shaonianzhentan/smtp#4]
![VeryCapture_20240923224439](https://github.com/user-attachments/assets/9e95e74c-2f79-4ebf-9beb-06ff66b141e9)
![VeryCapture_20240923224624](https://github.com/user-attachments/assets/ee249d96-c907-4fc2-b531-d8c0c8467a13)

作者你好，我安装这个集成，授权码确定是对的，但是显示配置有误

**Comment by shaonianzhentan** [comment]
这些开了吗？
![image](https://github.com/user-attachments/assets/b6f4b7fb-aad8-42a4-973d-cd0784f37e4b)

**Comment by haoyouandme** [comment]
> 这些开了吗？ ![image](https://private-user-images.githubusercontent.com/5294022/369931883-b6f4b7fb-aad8-42a4-973d-cd0784f37e4b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxMDQ1OTgsIm5iZiI6MTcyNzEwNDI5OCwicGF0aCI6Ii81Mjk0MDIyLzM2OTkzMTg4My1iNmY0YjdmYi1hYWQ4LTQyYTQtOTczZC1jZDA3ODRmMzdlNGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjNUMTUxMTM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDZlMmVkYmUwMTQ1MjE3NjFhOWE1YTg0MDY1YmJkMDE1OTU2Y2M3NjYwYmVkZTc1NjRmMTQ4N2FkYTc4ZTRmMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.JUcIa2A8a9wCAO9RatwUbdlC4a7930JrNibsuWSJFuY)

![VeryCapture_20240923231214](https://github.com/user-attachments/assets/50cc54a9-15fb-462a-afc6-f2be54812db5)
打开了的，因为smtp授权我也不是第一次用

**Comment by shaonianzhentan** [comment]
> 我这边测试都是没问题的

这是腾讯邮箱的服务域名`smtp.qq.com`，可以排查一下是否被拦截。

**Comment by haoyouandme** [comment]
### **作者你好：**
我把问题解决了，我不懂代码，是我用AI帮忙弄成的，你看看是否可以采纳。

### 解决方法：
\custom_components\smtp\qqmail.py 这一行代码：`server = smtplib.SMTP(smtp_server, 25)`
我把它修改成`server = smtplib.SMTP_SSL(smtp_server, 465)` 之后，成功配置，且可以接收到推送邮件了。
![image](https://github.com/user-attachments/assets/07a893b2-4b8c-48f4-af33-dd87d839ef37)
![image](https://github.com/user-attachments/assets/08ab85ad-96e2-4bd8-8e35-494e148dc958)
![image](https://github.com/user-attachments/assets/04600bd9-350f-4777-a875-777971bf474d)
![image](https://github.com/user-attachments/assets/55616cab-170c-4809-a763-8ce52e4927a6)
